### ISSUE TITLE
meta.genres

### ISSUE THREAD

**Issue by Ivshti** [Ivshti/stremio-addons#19]
we should define a method that serves all genres that should be implemented by all add-on clients and every add-on that actually needs it

currently genre list is built on the fly from items that we get from meta.find, which is not especially reliable if no items from a specific genre are returned in the top 70

@jaruba

**Comment by jaruba** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1777923/23170094/c1eff7ec-f856-11e6-86b1-6554f2e11051.gif)
