### ISSUE TITLE
poster examples in documentation - broken links

### ISSUE THREAD

**Issue by Ivshti** [Ivshti/stremio-addons#20]
tag @jaruba - any proposal for what we should use instead of the goo.gl links?

they are broken

e.g. http://goo.gl/xgCrG9 on https://github.com/Ivshti/stremio-addons/blob/master/docs/api/meta/meta.find.md

**Comment by jaruba** [comment]
do we still want / need a shortener for them? why were the links shortened in the first place? :)

**Comment by jaruba** [comment]
@Ivshti

**Comment by Ivshti** [comment]
@jaruba I don't know, you wrote it :) h

**Comment by jaruba** [comment]
![aha](https://cloud.githubusercontent.com/assets/1777923/23460272/3192d6e6-fe8d-11e6-94b1-cdb937bc8ed8.gif)
