### ISSUE TITLE
Stremio - A couple of minor issues in linux

### ISSUE THREAD

**Issue by Zeioth** [Ivshti/stremio-addons#3]
I really like this program, but I have found this issues. I hope you find them useful!

A) When you open the program, or reproduce any video, having more than 1 monitor, the window is centered between both monitors instead in the center of your main screen.

B) Would be great for usability if a left click in the notification area icon could toggle "show window".

C) The application shows no icon in the task bar in linux. (I had the same issue using slack, maybe it's an issue in electron?)

System: Ubuntu 15.10

**Comment by Ivshti** [comment]
Hi, I should close this issue because this is the github of the add-ons system.

Thanks for the feedback though.

A) - we should probably make an optio for that 
B) note taken, will see if possible with Electron
C) same thing - maybe issue with electron
